spring:
  profiles:
    active: dev
  application:
    name: security-oauth2-server
  http:
    encoding:
      charset: UTF-8
server:
  port: 12001
  contextPath: /v1
  display-name: security-oauth2-server
security:
  oauth2:
    client:
      client-id: clientapp
      client-secret: 123456
      scope: read,write
      auto-approve-scopes: '.*'
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/canary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  redis:
    cluster:
      nodes: 47.94.221.81:6379
      max-redirects: 10
      requirepass: foobared

---
spring:
  profiles: integration
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/canary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  redis:
    cluster:
      nodes: 47.94.221.81:6379
      max-redirects: 10
      requirepass: foobared

---
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/canary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  redis:
    cluster:
      nodes: 47.94.221.81:6379
      max-redirects: 10
      requirepass: foobared
