spring:
  profiles:
    active: dev
  application:
    name: pairs-common-oauth-server
  http:
    encoding:
      charset: UTF-8
server:
  port: 12001
  contextPath: /v1
  display-name: pairs-common-oauth-server
fortress:
  mybatis:
    enabled: true
  redis:
    enabled: true
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json
security:
  oauth2:
    client:
      client-id: clientapp
      client-secret: 123456
      scope: read,write
      auto-approve-scopes: '.*'
image:
  domain:
    url: http://www.duiduiche.com/shop/credentials/
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/canary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  redis:
    cluster:
      nodes: 47.94.221.81:6379
      max-redirects: 10
      requirepass: foobared
logback:
  behaviour:
    mongo: dev-behaviour-helper-mongo
    elasticsearch: dev-behaviour-helper-es
  log:
    elasticsearch: dev-log-helper-es

---
spring:
  profiles: integration
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/renren_fast?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  data:
    mongodb:
      uri: mongodb://paicheya:PCYpcy123@192.168.8.63,192.168.8.64/ocean?replicaSet=foba&authSource=admin
  redis:
    cluster:
      nodes: 192.168.8.90:6379,192.168.8.91:6379,192.168.8.93:6379,192.168.8.94:6379,192.168.8.96:6379,192.168.8.98:6379
      max-redirects: 10
logback:
  behaviour:
    mongo: inte-behaviour-helper-mongo
    elasticsearch: inte-behaviour-helper-es
  log:
    elasticsearch: inte-log-helper-es
---
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/renren_fast?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  data:
    mongodb:
      uri: mongodb://paicheya:PCYpcy123@172.16.8.63,172.16.8.64/ocean_prod?replicaSet=foba&authSource=admin
  redis:
    cluster:
      nodes: 192.168.6.5:6379,192.168.6.7:6379,192.168.6.13:6379,192.168.6.9:6379,192.168.6.14:6379,192.168.6.8:6379
      max-redirects: 10
logback:
  behaviour:
    mongo: prod-behaviour-helper-mongo
    elasticsearch: prod-behaviour-helper-es
  log:
    elasticsearch: prod-log-helper-es
